import Head from "next/head";
import About from "../../Components/About";
import Top from "../../Components/Top";
import Tecnologias from "../../Components/Tecnologias/index";
import styles from "./Home.module.css";
import Resumen from "../../Components/Resumen";
import Jobs from "../../Components/Jobs";
import Contacto from "../../Components/Contacto";
import Footer from "../../Components/Footer";
import Wpp from "../../Components/Wpp";

const Home = () => {
  return (
    <div>
      <Head>
        <title>Felipe Ballarino | Portfolio </title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <div className={styles.contenedor}>
        <Top></Top>
        <About></About>
        <Tecnologias></Tecnologias>
        <Resumen></Resumen>
        <Jobs></Jobs>
        {/* <Contacto></Contacto> */}
        <Wpp></Wpp>
        <Footer></Footer>
      </div>
    </div>
  );
};

export default Home;
